### ISSUE TITLE
embedded apostrophe  in single quoted string

### ISSUE THREAD

**Issue by scotthz** [RehanSaeed/Bash-Cheat-Sheet#1]
Syntax of case statements has quote/apostrophe issues (https://github.com/RehanSaeed/Bash-Cheat-Sheet#case-statements)
A couple single-quoted strings contain apostrophes used in contractions like don't and What's.

**Comment by RehanSaeed** [comment]
I think I've now fixed it. Thank you.

**Comment by scotthz** [comment]
It's a good cheat sheet, very useful and I appreciate the plaintext format, makes it easy to copy and paste templates/examples.
