### ISSUE TITLE
'ls 2>&1 out.txt' to 'ls 2>&1> out.txt' ?

### ISSUE THREAD

**Issue by nik-webdevelop** [RehanSaeed/Bash-Cheat-Sheet#5]
Thank you for this neat and useful cheatsheet ) 
In [this](https://github.com/RehanSaeed/Bash-Cheat-Sheet#standard-output-standard-error-and-standard-input) section,
should
**ls 2>&1 out.txt** # Redirect standard output and error to a file
 have **'>'** after 1 ?
**ls 2>&1> out.txt**

**Comment by khairahscorner** [comment]
@nik-webdevelop from the context explained with the comment, I believe you're right. created this PR #6 to correct it, hope that's fine!
